INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (1, '恰恰瓜子', 2.5, '零食');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (2, '太阳锅巴', 4, '零食');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (3, '品客薯片', 10, '零食');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (4, '可口可乐', 3, '饮料');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (5, '山海关', 3, '饮料');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (6, '现磨咖啡', 12, '饮料');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (7, '七星', 15, '香烟');
INSERT INTO GOODS (ID, NAME, PRICE, CATEGORY) VALUES (8, '中南海', 10, '香烟');
